const PLAYER_BORDER_VALUE = 28
const DEFAULT_COLOR = '#555555'
const DEFAULT_COLOR_2 = '#ffffff'
const BRIGHTNESS_THRESHOLD_WHITE = 240
const BRIGHTNESS_THRESHOLD_BLACK = 100
const MOBILE_THUMB_WIDHT = '75%'

export {PLAYER_BORDER_VALUE, DEFAULT_COLOR, DEFAULT_COLOR_2, BRIGHTNESS_THRESHOLD_WHITE, BRIGHTNESS_THRESHOLD_BLACK, MOBILE_THUMB_WIDHT}