const PLAYER_BORDER_VALUE = 28
const DEFAULT_COLOR = '#555555'
const BRIGHTNESS_THRESHOLD = 240
const MOBILE_THUMB_WIDHT = '75%'

export {PLAYER_BORDER_VALUE, DEFAULT_COLOR, BRIGHTNESS_THRESHOLD, MOBILE_THUMB_WIDHT}